apiVersion: feast.dev/v1
kind: FeatureStore
metadata:
  name: banking
  namespace: feast
  labels:
    feature-store-ui: enabled
spec:
  authz:
    oidc:
      secretRef:
        name: feast-oidc-secret
  feastProject: banking
  feastProjectDir:
    git:
      featureRepoPath: server_feature_repo
      ref: oidc-support
      url: 'https://github.com/aniketpalu/banking-feature-store.git'
  services:
    onlineStore:
      persistence:
        store:
          secretRef:
            name: feast-data-stores
          type: postgres
      server:
        image: quay.io/aniket-redhat/feature-server:oidc-dev-0.2
        logLevel: debug
    offlineStore:
      server:
        image: quay.io/aniket-redhat/feature-server:oidc-dev-0.2
        logLevel: debug
    registry:
      local:
        persistence:
          store:
            secretRef:
              name: feast-data-stores
            type: sql
        server:
          image: quay.io/aniket-redhat/feature-server:oidc-dev-0.2
          logLevel: debug
