apiVersion: v1
kind: Secret
metadata:
  name: feast-oidc-secret
  namespace: feast
type: Opaque
stringData:
  auth_discovery_url: "https://44.198.163.250/realms/apaluska-oidc/.well-known/openid-configuration"
  client_id: "odh-client"
  client_secret: "placeholder"
  username: "placeholder"
  password: "placeholder"
